---
title: "test for subsample of H938"
author: "Wei Wang"
date: 2017-02-17
output: html_document
---

```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

```{r knitr-opts-chunk, include=FALSE}
```

**Last updated:** `r Sys.Date()`

**Code version:** `r workflowr::extract_commit(".", 1)$sha1`

## full data

### 4 factors 

```{r}
Binflash = readRDS("~/HG/LogisticFlash_workflow/data/popgen/H398_K10.rds")
id_index = readRDS("~/HG/LogisticFlash_workflow/data/popgen/H938_colnames.rds")
id_index = sub(".*_", "", id_index)
id_index = data.frame(id_index)
library(ggplot2)
plot_df = data.frame(Binflash$f)
colnames(plot_df) = c("f1","f2","f3","f4")
```

```{r}
par(mfrow = c(2,2),mar = c(5,4,4,2) - 1.8)
for(i in 1:4) barplot(Binflash$f[,i])
```

### factors on the labels 

```{r}
data_label = read.table("~/HG/LogisticFlash_workflow/data/popgen/Euro.clst.txt",as.is = TRUE)
colnames(data_label) = c("n","id_index","country")
country = sapply(id_index$id_index,function(x){data_label$country[which(data_label$id_index == x)]})
```

### factor 1 vs factor 2

```{r}
p1 <- ggplot(plot_df, aes(f1, f2, label = (as.character(country) )), parse = FALSE)
# p + geom_text()
p1 + geom_label(aes(fill = country), colour = "white", fontface = "bold")
```

### factor 1 vs factor 3

```{r}
p2 <- ggplot(plot_df, aes(f1, f3, label = (as.character(country) )), parse = FALSE)
# p + geom_text()
p2 + geom_label(aes(fill = country), colour = "white", fontface = "bold")
```

### factor 2 vs factor 3

```{r}
p3 <- ggplot(plot_df, aes(f2, f3, label = (as.character(country) )), parse = FALSE)
# p + geom_text()
p3 + geom_label(aes(fill = country), colour = "white", fontface = "bold")
```

### factor 1 vs factor 4

```{r}
p3 <- ggplot(plot_df, aes(f1, f4, label = (as.character(country) )), parse = FALSE)
# p + geom_text()
p3 + geom_label(aes(fill = country), colour = "white", fontface = "bold")
```

### factor 2 vs factor 4

```{r}
p3 <- ggplot(plot_df, aes(f2, f4, label = (as.character(country) )), parse = FALSE)
# p + geom_text()
p3 + geom_label(aes(fill = country), colour = "white", fontface = "bold")
```

### factor 3 vs factor 4

```{r}
p3 <- ggplot(plot_df, aes(f3, f4, label = (as.character(country) )), parse = FALSE)
# p + geom_text()
p3 + geom_label(aes(fill = country), colour = "white", fontface = "bold")
```

## Session Information

```{r session-info}
```
